version: "3"
services:

  metabase-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: metabase-db
    networks:
      - metabase
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306

  metabase:
    image: metabase/metabase:latest
    restart: always
    container_name: metabase
    environment:
      MB_DB_TYPE: "mysql"
      MB_DB_DBNAME: "${DB_NAME}"
      MB_DB_PORT: "${DB_PORT}"
      MB_DB_USER: "${DB_USER}"
      MB_DB_PASS: "${DB_PASSWORD}"
      MB_DB_HOST: "metabase-db"

      MB_PASSWORD_COMPLEXITY: strong
      MB_PASSWORD_LENGTH: 8
      JAVA_TIMEZONE: "${MB_TIMEZONE}"
      JAVA_TOOL_OPTIONS: "-Xmx3072m"
    networks:
      - metabase
    ports:
      - "${MB_PORT}:3000"
    depends_on:
      - metabase-db

networks:
  metabase:
    driver: bridge

volumes:
  mysql:
